# Generated by Django 3.0.8 on 2020-09-16 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='created',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='updated',
        ),
    ]
