# Generated by Django 3.0.8 on 2020-08-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myonlineshop', '0002_myuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='date_joined',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phone_number',
            field=models.TextField(),
        ),
    ]
