# Generated by Django 3.1.1 on 2020-09-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myonlineshop', '0008_auto_20200920_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale',
            field=models.BooleanField(default=False, verbose_name='pending payments'),
        ),
    ]
