# Generated by Django 3.1.1 on 2020-09-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myonlineshop', '0009_auto_20200924_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.BooleanField(choices=[('Red', 'R'), ('Black', 'B')], default=True),
            preserve_default=False,
        ),
    ]
