# Generated by Django 3.1.1 on 2020-09-24 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myonlineshop', '0010_product_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
    ]
