# Generated by Django 3.1.1 on 2020-09-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myonlineshop', '0011_remove_product_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='header_image',
            field=models.BooleanField(default=False),
        ),
    ]
