# Generated by Django 3.1.1 on 2020-09-28 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myonlineshop', '0016_auto_20200929_0742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='ip',
        ),
    ]
