# Generated by Django 3.1.1 on 2020-09-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myonlineshop', '0018_auto_20200929_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.IntegerField(default=1, max_length=10),
        ),
    ]
