# Generated by Django 3.1.1 on 2020-09-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myonlineshop', '0019_auto_20200929_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.IntegerField(default=1),
        ),
    ]
