# Generated by Django 3.1.1 on 2020-10-03 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myonlineshop', '0022_variation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
