# Generated by Django 3.1.1 on 2020-10-06 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myonlineshop', '0023_delete_variation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_cloth', models.CharField(choices=[('S', 'Small'), ('L', 'Large')], default='Small', max_length=200)),
                ('size_trouser', models.CharField(choices=[(42, 42), (41, 41)], default=42, max_length=200)),
                ('product', models.ForeignKey(blank='True', null=True, on_delete=django.db.models.deletion.CASCADE, to='myonlineshop.product')),
            ],
        ),
    ]
