# Generated by Django 3.1.1 on 2020-10-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myonlineshop', '0025_auto_20201006_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='size_trouser',
            field=models.CharField(choices=[('42', '42'), ('41', '41')], max_length=200),
        ),
    ]
