# Generated by Django 3.1.1 on 2020-10-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myonlineshop', '0026_auto_20201006_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='size_cloth',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='size_trouser',
        ),
        migrations.AddField(
            model_name='variation',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='title',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variation',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
