# Generated by Django 3.1.1 on 2020-10-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myonlineshop', '0027_auto_20201006_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='Category',
            field=models.CharField(choices=[('size', 'size'), ('color', 'color'), ('package', 'package')], default='size', max_length=120),
        ),
    ]
