# Generated by Django 3.1.1 on 2020-10-06 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myonlineshop', '0028_variation_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='Category',
            new_name='category',
        ),
    ]
