# Generated by Django 3.1.1 on 2020-10-07 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myonlineshop', '0029_auto_20201006_2244'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
