# Generated by Django 3.1.1 on 2020-10-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myonlineshop', '0030_delete_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_cloth',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size_trouser',
            field=models.BooleanField(default=True),
        ),
    ]
