# Generated by Django 3.1.1 on 2020-10-10 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myonlineshop', '0031_auto_20201007_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='new',
            new_name='super_offer',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='recomended',
            new_name='super_offer2',
        ),
    ]
