# Generated by Django 3.1.1 on 2020-10-19 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myonlineshop', '0032_auto_20201010_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
    ]
