# Generated by Django 3.1.1 on 2020-10-28 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myonlineshop', '0036_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='variant',
            new_name='variant_product',
        ),
    ]
