# Generated by Django 3.1.1 on 2020-12-22 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myonlineshop', '0040_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
