# Generated by Django 3.1.1 on 2020-12-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myonlineshop', '0042_auto_20201225_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('True', 'True'), ('False', 'False')], default='New', max_length=10),
        ),
    ]
