# Generated by Django 3.1.1 on 2020-09-24 08:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myonlineshop', '0008_auto_20200920_1745'),
        ('order', '0003_auto_20200923_1721'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('user', 'order', 'product', 'price', 'quantity')},
        ),
    ]
