# Generated by Django 3.1.1 on 2020-10-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20200924_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(choices=[('L', 'Large'), ('S', 'small'), ('XL', 'Extra Large')], default='S', max_length=200),
        ),
    ]
