# Generated by Django 3.1.1 on 2020-10-07 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='size',
            new_name='size_cloth',
        ),
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
