# Generated by Django 3.1.1 on 2020-10-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20201007_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='size_cloth',
            field=models.CharField(choices=[('L', 'Large'), ('S', 'small'), ('XL', 'Extra Large')], max_length=200),
        ),
    ]
