# Generated by Django 3.1.1 on 2020-10-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_order_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='size_cloth',
            field=models.CharField(choices=[('L', 'Large'), ('S', 'small'), ('XL', 'Extra Large')], default='SM', max_length=200),
        ),
    ]
