# Generated by Django 3.1.1 on 2020-10-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_auto_20201007_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='size_cloth',
            field=models.CharField(choices=[('L', 'Large'), ('S', 'small'), ('XL', 'Extra Large')], default='S', max_length=200),
        ),
    ]
