# Generated by Django 3.1.1 on 2020-10-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_auto_20201014_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('Lagos', 'Lagos'), ('Ogun', 'Ogun')], default='Lagos', max_length=200),
        ),
    ]
